spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: ${url}
        username: ${db_username}
        password: ${db_password}

logging:
  level: error
  path: logs

mybatis:
    config-location: classpath:mybatis-config.xml
    type-aliases-package: hackday.webtoon.models

