mybatis:
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    mapper-locations: classpath*:**/mappers/*.xml

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/${db_name}
        username: ${db_username}
        password: ${db_password}

server:
    port: 8080

